### PR TITLE
Backport systemd-networkd-tests fixes

### PR DESCRIPTION
**Pull request by mrc0mmand**
My first attempt in backporting the systemd-networkd testsuite from upstream.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@ssahani it would be great if you could take a look as well if I didn't forget something important.

**Comment by mrc0mmand** [comment]
Note: this will require several other patches, as the code won't compile right now (both CIs compile it with `-Dnetworkd=false`)

**Comment by lnykryn** [comment]
@mrc0mmand Since we don't plan to ship networkd for el8, wouldn't make more sense just to drop those tests?

**Comment by ssahani** [comment]
I think it perfectly makes to include those at we should prepare for the future. adding tests would help us making the product better.

**Comment by ssahani** [comment]
Overall LGTM. It would be nice to see if you can attach the logs thanks !

**Comment by mrc0mmand** [comment]
> 
> 
> @mrc0mmand Since we don't plan to ship networkd for el8, wouldn't make more sense just to drop those tests?

For some reason I though we're going to ship it due to other dependencies. In that case I'm not sure if it's worth the hassle tracking down all necessary commits to make this work.

> 
> 
> Overall LGTM. It would be nice to see if you can attach the logs thanks !

I don't have the logs anymore, but you can reproduce it by simply compiling this PR.


As I finally re-enabled the networkd tests for the upstream repo (see https://github.com/systemd/systemd-centos-ci/pull/66) I'm not sure if the effort needed to do the same for downstream is worth it. However, if you're willing to take over this PR, @ssahani, it would be much appreciated, as I lack the knowledge and experience (and time as well) to backport the necessary patches.

**Comment by ssahani** [comment]
> > @mrc0mmand Since we don't plan to ship networkd for el8, wouldn't make more sense just to drop those tests?
> 
> For some reason I though we're going to ship it due to other dependencies. In that case I'm not sure if it's worth the hassle tracking down all necessary commits to make this work.
> 
> > Overall LGTM. It would be nice to see if you can attach the logs thanks !
> 
> I don't have the logs anymore, but you can reproduce it by simply compiling this PR.
> 

No issues I am going to run this in a one minute machine.

> As I finally re-enabled the networkd tests for the upstream repo (see [systemd/systemd-centos-ci#66](https://github.com/systemd/systemd-centos-ci/pull/66)) I'm not sure if the effort needed to do the same for downstream is worth it. 

Yes it does . I see a lots of ppl are asking for it . before release we need to run tests. Running tests no harm rather it's better.

>However, if you're willing to take over this PR, @ssahani, it would be much appreciated, as I lack the knowledge and experience (and time as well) to backport the necessary patches.

Sure. I have to say you are doing great work . Thanks for working on this. Much appreciated.

**Comment by lnykryn** [comment]
To be honest I would vote for dropping this. We don't care if any part of networkd brakes in rhel and it will only make the CI runs a bit longer.

**Comment by ssahani** [comment]
> To be honest I would vote for dropping this. We don't care if any part of networkd brakes in rhel and it will only make the CI runs a bit longer.

Isn't it running separate to systemd tests that can be figured out which test cases failed. Running longer is not a issue. It's not a performance use case surely.

**Comment by lnykryn** [comment]
@ssahani  but again, why should we run those in the first place? We build systemd with -Dnetworkd=false in the spec file.

**Comment by ssahani** [comment]
> @ssahani but again, why should we run those in the first place? We build systemd with -Dnetworkd=false in the spec file.

This makes sense. Only should be run where it needed. That can be configured I guess.

**Comment by lnykryn** [comment]
After a discussion with @mrc0mmand we have agreed that we can close this one.

**Pull request closed without merging**
