### PR TITLE
(#1705971) RHEL 8 LGTM fixes

### PR DESCRIPTION
**Pull request by mrc0mmand**
Several fixes for warnings found by LGTM.

### CODE REVIEW

**Comment by lnykryn** [comment]
This pull request **fixes 6 alerts** when merging c2bb19df308954d983620ee3c12e1b95d331ec54 into d26406cc3f2c186691ce0a09052d3c39d15cc722 - [view on LGTM.com](https://lgtm.com/projects/g/lnykryn/systemd-rhel/rev/pr-341587d6e68434d924ac4ded04e9a1d6c4d5c4dc)

**fixed alerts:**

* 6 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by mrc0mmand** [comment]
The remaining LGTM warnings are related to systemd parts, which have been removed from systemd upstream, namely:

- python-systemd: moved to a separate repository (systemd/python-systemd) in 2799e519cabb6dfa99341b9a56ebd4dc2a4ec22a
- libsystemd-terminal/systemd-consoled: dropped completely in d537694a987bbb01e780bd5abe9412722fc38faa
- gudev/gtk-doc: moved to a separate repository in 2375607039517c88df51ef16ddbb624ec1c10654

We can either follow the upstream path or just waive these warnings in LGTM.

**Comment by lnykryn** [comment]
This pull request **fixes 8 alerts** when merging 18eb081e9f9b176359e9bb39e6d7f4ee60c391f6 into d26406cc3f2c186691ce0a09052d3c39d15cc722 - [view on LGTM.com](https://lgtm.com/projects/g/lnykryn/systemd-rhel/rev/pr-5868abc51dbcd23eb3e6c819066272ce57a202a1)

**fixed alerts:**

* 6 for Missing variable declaration
* 1 for Unused local variable
* 1 for Unneeded defensive code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by lnykryn** [comment]
This pull request **fixes 8 alerts** when merging 3234378060349a2c51b08b075d5ee47429123643 into 16d1f6e5122038fa24392e166a0a88c6cab41dd0 - [view on LGTM.com](https://lgtm.com/projects/g/lnykryn/systemd-rhel/rev/pr-b5b5af21b7cc3d1a891275c84e95d4f8316e611a)

**fixed alerts:**

* 6 for Missing variable declaration
* 1 for Unused local variable
* 1 for Unneeded defensive code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by msekletar** [comment]
I have created a BZ to match this PR.

https://bugzilla.redhat.com/show_bug.cgi?id=1705971

**Review by msekletar — CHANGES_REQUESTED** [review]
Please use reference rhbz #1705971 in all commit messages.

Otherwise looks OK.

**Comment by mrc0mmand** [comment]
Pushed a new version with correct Resolves: lines, PTAL!

**Comment by lnykryn** [comment]
This pull request **fixes 8 alerts** when merging 6aeb0790b7ec2184162220d9a3016a6a88cc6c81 into f5bd75fb574b9be80879fda5a889ddfd2b706248 - [view on LGTM.com](https://lgtm.com/projects/g/lnykryn/systemd-rhel/rev/pr-f1fad0a006651f96e40b7a2f43d5869b1e502836)

**fixed alerts:**

* 6 for Missing variable declaration
* 1 for Unused local variable
* 1 for Unneeded defensive code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by msekletar — APPROVED** [review]

**Pull request merged**
