### PR TITLE
C LGTM analysis for RHEL 8

### PR DESCRIPTION
**Pull request by mrc0mmand**
Let's add a custom config for LGTM so the C part systemd can be compiled and properly analyzed.

### CODE REVIEW

**Comment by lnykryn** [comment]
This pull request **introduces 1 alert** and **fixes 5** when merging 06809b7440027e3963ffa1a257918c9db858ccaf into c95026c6979bb6f8dc52a6392318bc16615ace77 - [view on LGTM.com](https://lgtm.com/projects/g/lnykryn/systemd-rhel/rev/pr-154f827207c5a939c9f62839008ce2a5228b69ad)

**new alerts:**

* 1 for Syntax error

**fixed alerts:**

* 2 for Syntax error
* 2 for Encoding error
* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by lnykryn** [comment]
This pull request **fixes 4 alerts** when merging 77210ba48563659722acafe888bdc14e3b2fe15b into c95026c6979bb6f8dc52a6392318bc16615ace77 - [view on LGTM.com](https://lgtm.com/projects/g/lnykryn/systemd-rhel/rev/pr-f79250f28516bfd5c3ff399f2559f11807983a98)

**fixed alerts:**

* 2 for Syntax error
* 2 for Encoding error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by lnykryn** [comment]
This pull request **fixes 4 alerts** when merging 86bed5c11a9af3aa57d06a8346b8e8a4cc903e6d into c95026c6979bb6f8dc52a6392318bc16615ace77 - [view on LGTM.com](https://lgtm.com/projects/g/lnykryn/systemd-rhel/rev/pr-aef8150a1cb50f48e5ceb208e9d737bc4b718856)

**fixed alerts:**

* 2 for Syntax error
* 2 for Encoding error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by mrc0mmand** [comment]
So, the C analysis *should* work after merging this PR.

Taken from LGTM support forum:

> Currently, unfortunately it’s not possible for users to configure which languages are analysed for a particular project once that project has already been added to LGTM.com (we’re working on improving this as we speak). In particular, modifying a lgtm.yml file in a Pull Request (like you have done here) will not cause the additional language to be analysed for that pull request.
> For an additional language to be added to LGTM, we need to be able to build the default branch of a repository. 

We may need to fix the LGTM for the `staging` branch first, though, if I understand the statement above correctly...

**Pull request merged**
