### PR TITLE
travis: build & test systemd with ASan and UBSan on RHEL7

### PR DESCRIPTION
**Pull request by mrc0mmand**
Let's build & test systemd with Address Sanitizer and Undefined Behavior Sanitizer in Travis.

Marked as WIP as this has to be resolved & tested separately for staging and staging-next branches.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
It looks like gcc4 is too old for ASan to work properly:

```
    Making all in docs/libudev
    Making all in docs/gudev
      DOC   Scanning header files
      DOC   Introspecting gobjects
    2019-01-23 08:00:26,135:scangobj.py:execute_command:1196:WARNING:Running scanner failed: -11, command: /bin/sh ../../libtool --mode=execute ./gudev-scan
    make[2]: *** [scan-build.stamp] Error 245
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2
    [root@host-8-252-40 systemd-219]# gdb /root/rpmbuild/BUILD/systemd-219/docs/gudev/.libs/lt-gudev-scan
    GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>...
    Reading symbols from /root/rpmbuild/BUILD/systemd-219/docs/gudev/.libs/lt-gudev-scan...done.
    (gdb) run
    Starting program: /root/rpmbuild/BUILD/systemd-219/docs/gudev/.libs/lt-gudev-scan
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
     
    Program received signal SIGSEGV, Segmentation fault.
    0x0000000000000000 in ?? ()
    (gdb) bt full
    #0  0x0000000000000000 in  ()
    #1  0x00007ffff2db4404 in __asan::MaybeInstallSigaction(int, void (*)(int, siginfo_t*, void*)) (signum=signum@entry=11, handler=
        0x7ffff2db4360 <__asan::ASAN_OnSIGSEGV(int, siginfo_t*, void*)>) at ../../../../libsanitizer/asan/asan_posix.cc:39
            sigact =
              {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 0, 0, 0, 0, 0, 0, 0, 0, 18446744073699065856, 18446744073699069952, 140737353973760, 140737267879458, 0, 140737353987135, 140737272503952}}, sa_flags = -220471292, sa_restorer = 0x2008fff7000}
    #2  0x00007ffff2db46a2 in __asan::InstallSignalHandlers() (handler=
        0x7ffff2db4360 <__asan::ASAN_OnSIGSEGV(int, siginfo_t*, void*)>, signum=11) at ../../../../libsanitizer/asan/asan_posix.cc:94
    #3  0x00007ffff2db46a2 in __asan::InstallSignalHandlers() () at ../../../../libsanitizer/asan/asan_posix.cc:92
    #4  0x00007ffff2db57fb in __asan_init_v1() () at ../../../../libsanitizer/asan/asan_rtl.cc:500
            options = <optimized out>
            shadow_start = 2147446784
            shadow_end = 17594333495295
            full_shadow_is_available = true
    #5  0x00007ffff77cc907 in _GLOBAL__sub_I_00099_1_libudev.c () at src/libudev/libudev.c:252
    #6  0x00007ffff7dea903 in _dl_init (env=0x7fffffffe538, argv=0x7fffffffe528, argc=1, l=<optimized out>) at dl-init.c:82
            j = <optimized out>
            jm = <optimized out>
            addrs = <optimized out>
            init_array = <optimized out>
            env = 0x7fffffffe538
            argv = 0x7fffffffe528
            argc = 1
            l = <optimized out>
            preinit_array = <optimized out>
            preinit_array_size = <optimized out>
            i = 2
    #7  0x00007ffff7dea903 in _dl_init (main_map=0x7ffff7ffe150, argc=1, argv=0x7fffffffe528, env=0x7fffffffe538) at dl-init.c:131
            preinit_array = <optimized out>
            preinit_array_size = <optimized out>
            i = 2
    #8  0x00007ffff7ddc15a in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
    #9  0x0000000000000001 in  ()
    #10 0x00007fffffffe776 in  ()
    #11 0x0000000000000000 in  ()
```

Using gcc6/gcc7 solves this issue.

**Comment by mrc0mmand** [comment]
Blocked by https://bugzilla.redhat.com/show_bug.cgi?id=1669117

**Comment by mrc0mmand** [comment]
As this issue wouldn't let me sleep, I dug a little bit deeper, and after a painstakingly significant amount of time and several workarounds later I finally managed to compile & run systemd under ASan on RHEL 7. The ASan detected several memory leaks, so they should be fixed prior merging this PR.

Applied workarounds (only the "relevant" ones, the rest is described in the code itself):
1) GCC 8 from SCL (devtools-8)
There's a bug somewhere in the GCC 4 which causes unexpected segfaults in some applications when compiled with ASan (see the relevant [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1669117)), so the best choice is to use a newer GCC. To get the best possible support I went with GCC 8 which works surprisingly well with the RHEL7 systemd.

2) Disabled warnings from newer GCCs
Several warnings were triggering the `-Werror` option a thus had to be disabled (if permanently of just temporarily has to be decided yet). Namely:
- `-Wimplicit-fallthrough=0`
- `-Wformat-truncation=0`
- `-Wno-cast-function-type`
- `-Wno-logical-op`

3) `make` has to be run with `LD_PRELOAD=/lib64/libasan.so*`
There's a known bug in GObject introspect which fails to handle ASan options during compilation, which causes unexpected errors in `GISCAN` phases of the build. Running the build with "correct" `LD_PRELOAD` fixes this issue, but causes significant slowdown (and breaks the compilation thanks to the memory leak check). Combination of `LD_PRELOAD` and `ASAN_OPTIONS=detect_leaks=false` allows the compilation to finish successfully in a reasonable time (however, the workaround itself is pretty ugly).

[This is the first job](https://travis-ci.org/lnykryn/systemd-rhel/jobs/485628356) which finished "successfully" (i.e. without compilation error), however it's missing the verbose test log. That *should* be fixed in https://travis-ci.org/lnykryn/systemd-rhel/jobs/485774546 once it finishes (Edit: the "interesting" part begins at https://travis-ci.org/lnykryn/systemd-rhel/jobs/485774546#L5126).

I'm not sure which workarounds we want to keep and which ones we'd like to fix, so feedback is definitely welcome (@msekletar).

Edit2: I disabled several other checks during the `make` phase to speed the compilation a little bit.

**Comment by mrc0mmand** [comment]
Here's a run with both ASan and UBSan enabled: https://travis-ci.org/lnykryn/systemd-rhel/jobs/485858249#L5141

**Comment by jsynacek** [comment]
What is the status of this PR? Is it still WIP and therefore not supposed to be merged?

**Comment by mrc0mmand** [comment]
I'd leave this PR in WIP, as it still needs a lot of work due to missing backports. However, the RHEL8 counterpart in https://github.com/lnykryn/systemd-rhel/pull/309 is ready to go.

**Pull request closed without merging**
